name: Publish
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest,ubuntu-20.04,windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Set platform variable
        if: matrix.platform == 'ubuntu-20.04' || matrix.platform == 'macos-latest'
        run: |
          if [[ "${{ matrix.platform }}" == "macos-latest" ]]; then
            echo "TRUNK_RELEASE=trunk-x86_64-apple-darwin.tar.gz" >> $GITHUB_ENV
          elif [[ "${{ matrix.platform }}" == "ubuntu-20.04" ]]; then
            echo "TRUNK_RELEASE=trunk-x86_64-unknown-linux-gnu.tar.gz" >> $GITHUB_ENV
          fi

      - name: Install trunk and tailwindcss (Mac and Linux)
        if: matrix.platform == 'ubuntu-20.04' || matrix.platform == 'macos-latest'
        run: |
          npm i -g tailwindcss
          TRUNK_RELEASE="${{env.TRUNK_RELEASE}}"
          wget -qO- https://github.com/thedodd/trunk/releases/download/v0.16.0/$TRUNK_RELEASE | tar -xzf-
          chmod +x trunk
          mv trunk /usr/local/bin
          rustup target add wasm32-unknown-unknown

      - name: Install trunk and tailwindcss (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          npm i -g tailwindcss
          Invoke-WebRequest -Uri "https://github.com/thedodd/trunk/releases/download/v0.16.0/trunk-x86_64-pc-windows-msvc.zip" -OutFile "trunk-x86_64-pc-windows-msvc.zip"
          Expand-Archive -Path "trunk-x86_64-pc-windows-msvc.zip" -DestinationPath "frontend"
          $relativePath = "frontend\trunk.exe"
          $fullPath = Join-Path -Path (Get-Location) -ChildPath $relativePath
          $env:Path += ";" + $fullPath
          rustup target add wasm32-unknown-unknown

      - name: Build and Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v0.0.1 # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'Tom Do Chess Bot v0.0.1'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false